#!/bin/bash

# Ensure the correct command is found:
export PATH="/software/rd/saturne/code_saturne/7.0/arch/cronos_ompi/bin":$PATH

# Insert default command
cs_cmd=""
if test $# = 1; then
  if test -f $1; then
    cs_cmd=gui
  fi
elif test $# = 0; then
  cs_cmd=gui
fi

# Run command
\code_saturne $cs_cmd "$@"
